### ISSUE TITLE
BME280 initialization failed: Error: EACCES: permission denied, open '/dev/i2c-1' 

### ISSUE THREAD

**Issue by Travisco29** [rxseger/homebridge-bme280#15]
Keep getting this with multiple bme280 plugins. Help?

**Comment by Travisco29** [comment]
Never mind, i fixed it. 
every time on rpi startup, run
`sudo chgrp i2c /dev/i2c-1`
`sudo chmod 666 /dev/i2c-1`

**Comment by lbilharz** [comment]
> every time on rpi startup, run

could you tell me why this needs to run after each boot?

(I'm asking as I have both a Pi Zero and a Pi 4, and only the latter needs it after reboot. For the Zero it was sufficient to change the permissions once and BME280 is initialising fine after rebooting.)
