### ISSUE TITLE
Multiple BME280 sensors

### ISSUE THREAD

**Issue by jos149** [rxseger/homebridge-bme280#19]
Dear reader,

My idea is to add another BME280 sensor to measure the temperature and humidity outdoor (additionally to my room temp/hum). However, how should I add this? I think there are two options:
1. Attach the second sensor to the pi over the same sda scl connectors.
2. Attach the second sensor to another device (pi zero or arduino for example) and send the data over the network.

However, I have not yet managed to get this to work. For option 1 my questions are:
is it possible to connect this sensor in parallel and obtain a unique adress?

For option 2 my questions are:
is it possible to send the BME280 data over the network? If yes, what address should I fill in (guess it should be ip related)?

**Comment by NorthernMan54** [comment]
For option 1 you would need to change the i2c address on you second bme280 board, and create a second instance of the bme280 accessory in the homebridge config.json with the second address.  I have never tried this, so it may not work but it should.

For option 2, you need to look for a different plugin for connecting to a remote bme280 connected to an esp8266. ( The esp8266 is the current goto device for creating WiFi enabled things, as it is cheap and support WiFi ) There are a few different ones out there, so some research is required.
