### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mv1993** [rxseger/homebridge-bme280#3]
Hello, I have read that the BME280 is capable of measuring the pressure. Is it possible to implement this in your plugin?
Thanks.

**Comment by NorthernMan54** [comment]
Take a look at my pull request, it implements barometric pressure and polling.  The only gotcha with barometric pressure it that it is not supported by the Home app only 3rd parties like eve.

You can install it with

npm install -g https://github.com/NorthernMan54/homebridge-bme280

**Comment by mv1993** [comment]
I will try it.

Thank you

**Comment by rxseger** [comment]
https://github.com/rxseger/homebridge-bme280/issues/4
https://github.com/rxseger/homebridge-bme280/pull/2
merged in https://github.com/rxseger/homebridge-bme280/commit/03011fbbd7d1f9def177d5bc882d0099e147ba8d
