### ISSUE TITLE
Error: BME280 Not Initalized

### ISSUE THREAD

**Issue by theGeorg** [rxseger/homebridge-bme280#7]
Homebridge is loading and everything is running but every time the data of the sensor is polled (every minute) I get the message 

`[Date] [Sensor] Error: BME280 Not Initalized`

Sensor is working fine using for example [this script](https://www.raspberrypi-spy.co.uk/2016/07/using-bme280-i2c-temperature-pressure-sensor-in-python/).

Any idea?

**Comment by NorthernMan54** [comment]
I’m wondering if it’s this

Since bme280-sensor needs to talk directly to the I2C bus and requires access to /dev/i2c, you will typically need run Node with elevated privileges or add your user account to the i2c group: $ sudo adduser $USER i2c

**Comment by theGeorg** [comment]
@NorthernMan54 
Thanks for the reply. 

I have done `$ sudo adduser $USER i2c` for my `pi` and `homebridge` accounts.

How do I run Node with elevated privileges?

When I start up homebridge I get this error message: 


[2018-2-21 00:47:15] [Sensor] BME280 initialization failed: { Error: Could not locate the bindings file. Tried:  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/Debug/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/Release/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/out/Debug/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/Debug/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/out/Release/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/Release/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/default/i2c.node  
 → /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/compiled/9.4.0/linux/arm/i2c.node  
    at bindings (/usr/local/lib/node_modules/homebridge-bme280/node_modules/bindings/bindings.js:93:9)  
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/i2c-bus.js:4:28)  
    at Module._compile (module.js:660:30)  
    at Object.Module._extensions..js (module.js:671:10)  
    at Module.load (module.js:573:32)  
    at tryModuleLoad (module.js:513:12)  
    at Function.Module._load (module.js:505:3)  
    at Module.require (module.js:604:17)  
    at require (internal/module.js:11:18)  
    at new BME280 (/usr/local/lib/node_modules/homebridge-bme280/node_modules/bme280-sensor/BME280.js:12:17)  
  tries:   
   [ '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/Debug/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/Release/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/out/Debug/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/Debug/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/out/Release/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/Release/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/build/default/i2c.node',  
     '/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/compiled/9.4.0/linux/arm/i2c.node' ] }

**Comment by NorthernMan54** [comment]
You shouldn’t need to.  In my environment I run it with normal permissions

Looking at that message, and it looks like the install had failed.

Try this

1) Remove homebridge-bme280

sudo rm -rf  /usr/local/lib/node_modules/homebridge-bme280

2) Reinstall homebridge-bme280, I presume you used the version from Instructables

sudo su
sudo npm install -g https://github.com/NorthernMan54/homebridge-bme280

Try that and if you get an error from the install please share.

**Comment by theGeorg** [comment]
My output:

```
pi@raspberrypi:~ $ sudo rm -rf  /usr/local/lib/node_modules/homebridge-bme280
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# sudo npm install -g https://github.com/NorthernMan54/homebridge-bme280

> i2c-bus@1.2.5 install /usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/9.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/.node-gyp/9.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-bme280/node_modules/i2c-bus/.node-gyp"
```

....(repeating those last lines as long as I stop it. )

**Comment by NorthernMan54** [comment]
Okay, you must be on the recent version of npm/nodejs

Try this

> sudo rm -rf /usr/local/lib/node_modules/homebridge-bme280
> 
> sudo su
> sudo npm install -g —unsafe-perm https://github.com/NorthernMan54/homebridge-bme280 <https://github.com/NorthernMan54/homebridge-bme280>

**Comment by theGeorg** [comment]
Yes. Thank you very much! Now it is working.

**Comment by NorthernMan54** [comment]
Awesome

**Comment by jos149** [comment]
Running into a similar issue! I am installing plugins in homebridge-ui in the browser. Does this mean I should remove the plugin there and install it again over the terminal with root privileges?
